language: node_js
nodejs:
- 6.9.1
notifications:
  email:
    onfailure: change
    onsuccess: change
addons:
  sshknownhosts:
  - 178.128.92.164
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/easygo-server/
  - REMOTEUSER=deploy
  - REMOTEHOST=178.128.92.164
  - PORT=8080
beforeinstall:
- npm install -g npm@^2
install:
- npm install --only=dev
beforescript:
- chmod 600 deploy && mv deploy ~/.ssh/idrsa
script:
- npm run dev
after_success:
- "./scripts/deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_344d275598f3_key -iv $encrypted_344d275598f3_iv
  -in deploy.enc -out deploy -d
